call javaapi#namespace('android.test.mock')

call javaapi#class('MockApplication', '', [
  \ javaapi#method(0,'MockApplication(', ')', 'public'),
  \ javaapi#method(0,'onCreate(', ')', 'void'),
  \ javaapi#method(0,'onTerminate(', ')', 'void'),
  \ javaapi#method(0,'onConfigurationChanged(', 'Configuration)', 'void'),
  \ ])

call javaapi#class('MockCursor', 'Cursor', [
  \ javaapi#method(0,'MockCursor(', ')', 'public'),
  \ javaapi#method(0,'getColumnCount(', ')', 'int'),
  \ javaapi#method(0,'getColumnIndex(', 'String)', 'int'),
  \ javaapi#method(0,'getColumnIndexOrThrow(', 'String)', 'int'),
  \ javaapi#method(0,'getColumnName(', 'int)', 'String'),
  \ javaapi#method(0,'getColumnNames(', ')', 'String[]'),
  \ javaapi#method(0,'getCount(', ')', 'int'),
  \ javaapi#method(0,'isNull(', 'int)', 'boolean'),
  \ javaapi#method(0,'getInt(', 'int)', 'int'),
  \ javaapi#method(0,'getLong(', 'int)', 'long'),
  \ javaapi#method(0,'getShort(', 'int)', 'short'),
  \ javaapi#method(0,'getFloat(', 'int)', 'float'),
  \ javaapi#method(0,'getDouble(', 'int)', 'double'),
  \ javaapi#method(0,'getBlob(', 'int)', 'byte[]'),
  \ javaapi#method(0,'getString(', 'int)', 'String'),
  \ javaapi#method(0,'getExtras(', ')', 'Bundle'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'isAfterLast(', ')', 'boolean'),
  \ javaapi#method(0,'isBeforeFirst(', ')', 'boolean'),
  \ javaapi#method(0,'isFirst(', ')', 'boolean'),
  \ javaapi#method(0,'isLast(', ')', 'boolean'),
  \ javaapi#method(0,'move(', 'int)', 'boolean'),
  \ javaapi#method(0,'moveToFirst(', ')', 'boolean'),
  \ javaapi#method(0,'moveToLast(', ')', 'boolean'),
  \ javaapi#method(0,'moveToNext(', ')', 'boolean'),
  \ javaapi#method(0,'moveToPrevious(', ')', 'boolean'),
  \ javaapi#method(0,'moveToPosition(', 'int)', 'boolean'),
  \ javaapi#method(0,'copyStringToBuffer(', 'int, CharArrayBuffer)', 'void'),
  \ javaapi#method(0,'deactivate(', ')', 'void'),
  \ javaapi#method(0,'close(', ')', 'void'),
  \ javaapi#method(0,'isClosed(', ')', 'boolean'),
  \ javaapi#method(0,'requery(', ')', 'boolean'),
  \ javaapi#method(0,'registerContentObserver(', 'ContentObserver)', 'void'),
  \ javaapi#method(0,'registerDataSetObserver(', 'DataSetObserver)', 'void'),
  \ javaapi#method(0,'respond(', 'Bundle)', 'Bundle'),
  \ javaapi#method(0,'getWantsAllOnMoveCalls(', ')', 'boolean'),
  \ javaapi#method(0,'setNotificationUri(', 'ContentResolver, Uri)', 'void'),
  \ javaapi#method(0,'unregisterContentObserver(', 'ContentObserver)', 'void'),
  \ javaapi#method(0,'unregisterDataSetObserver(', 'DataSetObserver)', 'void'),
  \ javaapi#method(0,'getType(', 'int)', 'int'),
  \ ])

call javaapi#class('MockDialogInterface', 'DialogInterface', [
  \ javaapi#method(0,'MockDialogInterface(', ')', 'public'),
  \ javaapi#method(0,'cancel(', ')', 'void'),
  \ javaapi#method(0,'dismiss(', ')', 'void'),
  \ ])

call javaapi#class('MockPackageManager', '', [
  \ javaapi#method(0,'MockPackageManager(', ')', 'public'),
  \ javaapi#method(0,'getPackageInfo(', 'String, int) throws NameNotFoundException', 'PackageInfo'),
  \ javaapi#method(0,'currentToCanonicalPackageNames(', 'String[])', 'String[]'),
  \ javaapi#method(0,'canonicalToCurrentPackageNames(', 'String[])', 'String[]'),
  \ javaapi#method(0,'getLaunchIntentForPackage(', 'String)', 'Intent'),
  \ javaapi#method(0,'getPackageGids(', 'String) throws NameNotFoundException', 'int[]'),
  \ javaapi#method(0,'getPermissionInfo(', 'String, int) throws NameNotFoundException', 'PermissionInfo'),
  \ javaapi#method(0,'queryPermissionsByGroup(', 'String, int) throws NameNotFoundException', 'PermissionInfo>'),
  \ javaapi#method(0,'getPermissionGroupInfo(', 'String, int) throws NameNotFoundException', 'PermissionGroupInfo'),
  \ javaapi#method(0,'getAllPermissionGroups(', 'int)', 'PermissionGroupInfo>'),
  \ javaapi#method(0,'getApplicationInfo(', 'String, int) throws NameNotFoundException', 'ApplicationInfo'),
  \ javaapi#method(0,'getActivityInfo(', 'ComponentName, int) throws NameNotFoundException', 'ActivityInfo'),
  \ javaapi#method(0,'getReceiverInfo(', 'ComponentName, int) throws NameNotFoundException', 'ActivityInfo'),
  \ javaapi#method(0,'getServiceInfo(', 'ComponentName, int) throws NameNotFoundException', 'ServiceInfo'),
  \ javaapi#method(0,'getProviderInfo(', 'ComponentName, int) throws NameNotFoundException', 'ProviderInfo'),
  \ javaapi#method(0,'getInstalledPackages(', 'int)', 'PackageInfo>'),
  \ javaapi#method(0,'checkPermission(', 'String, String)', 'int'),
  \ javaapi#method(0,'addPermission(', 'PermissionInfo)', 'boolean'),
  \ javaapi#method(0,'addPermissionAsync(', 'PermissionInfo)', 'boolean'),
  \ javaapi#method(0,'removePermission(', 'String)', 'void'),
  \ javaapi#method(0,'checkSignatures(', 'String, String)', 'int'),
  \ javaapi#method(0,'checkSignatures(', 'int, int)', 'int'),
  \ javaapi#method(0,'getPackagesForUid(', 'int)', 'String[]'),
  \ javaapi#method(0,'getNameForUid(', 'int)', 'String'),
  \ javaapi#method(0,'getInstalledApplications(', 'int)', 'ApplicationInfo>'),
  \ javaapi#method(0,'resolveActivity(', 'Intent, int)', 'ResolveInfo'),
  \ javaapi#method(0,'queryIntentActivities(', 'Intent, int)', 'ResolveInfo>'),
  \ javaapi#method(0,'queryIntentActivityOptions(', 'ComponentName, Intent[], Intent, int)', 'ResolveInfo>'),
  \ javaapi#method(0,'queryBroadcastReceivers(', 'Intent, int)', 'ResolveInfo>'),
  \ javaapi#method(0,'resolveService(', 'Intent, int)', 'ResolveInfo'),
  \ javaapi#method(0,'queryIntentServices(', 'Intent, int)', 'ResolveInfo>'),
  \ javaapi#method(0,'resolveContentProvider(', 'String, int)', 'ProviderInfo'),
  \ javaapi#method(0,'queryContentProviders(', 'String, int, int)', 'ProviderInfo>'),
  \ javaapi#method(0,'getInstrumentationInfo(', 'ComponentName, int) throws NameNotFoundException', 'InstrumentationInfo'),
  \ javaapi#method(0,'queryInstrumentation(', 'String, int)', 'InstrumentationInfo>'),
  \ javaapi#method(0,'getDrawable(', 'String, int, ApplicationInfo)', 'Drawable'),
  \ javaapi#method(0,'getActivityIcon(', 'ComponentName) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,'getActivityIcon(', 'Intent) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,'getDefaultActivityIcon(', ')', 'Drawable'),
  \ javaapi#method(0,'getApplicationIcon(', 'ApplicationInfo)', 'Drawable'),
  \ javaapi#method(0,'getApplicationIcon(', 'String) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,'getActivityLogo(', 'ComponentName) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,'getActivityLogo(', 'Intent) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,'getApplicationLogo(', 'ApplicationInfo)', 'Drawable'),
  \ javaapi#method(0,'getApplicationLogo(', 'String) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,'getText(', 'String, int, ApplicationInfo)', 'CharSequence'),
  \ javaapi#method(0,'getXml(', 'String, int, ApplicationInfo)', 'XmlResourceParser'),
  \ javaapi#method(0,'getApplicationLabel(', 'ApplicationInfo)', 'CharSequence'),
  \ javaapi#method(0,'getResourcesForActivity(', 'ComponentName) throws NameNotFoundException', 'Resources'),
  \ javaapi#method(0,'getResourcesForApplication(', 'ApplicationInfo)', 'Resources'),
  \ javaapi#method(0,'getResourcesForApplication(', 'String) throws NameNotFoundException', 'Resources'),
  \ javaapi#method(0,'getPackageArchiveInfo(', 'String, int)', 'PackageInfo'),
  \ javaapi#method(0,'setInstallerPackageName(', 'String, String)', 'void'),
  \ javaapi#method(0,'getInstallerPackageName(', 'String)', 'String'),
  \ javaapi#method(0,'addPackageToPreferred(', 'String)', 'void'),
  \ javaapi#method(0,'removePackageFromPreferred(', 'String)', 'void'),
  \ javaapi#method(0,'getPreferredPackages(', 'int)', 'PackageInfo>'),
  \ javaapi#method(0,'setComponentEnabledSetting(', 'ComponentName, int, int)', 'void'),
  \ javaapi#method(0,'getComponentEnabledSetting(', 'ComponentName)', 'int'),
  \ javaapi#method(0,'setApplicationEnabledSetting(', 'String, int, int)', 'void'),
  \ javaapi#method(0,'getApplicationEnabledSetting(', 'String)', 'int'),
  \ javaapi#method(0,'addPreferredActivity(', 'IntentFilter, int, ComponentName[], ComponentName)', 'void'),
  \ javaapi#method(0,'clearPackagePreferredActivities(', 'String)', 'void'),
  \ javaapi#method(0,'getPreferredActivities(', 'List<IntentFilter>, List<ComponentName>, String)', 'int'),
  \ javaapi#method(0,'getSystemSharedLibraryNames(', ')', 'String[]'),
  \ javaapi#method(0,'getSystemAvailableFeatures(', ')', 'FeatureInfo[]'),
  \ javaapi#method(0,'hasSystemFeature(', 'String)', 'boolean'),
  \ javaapi#method(0,'isSafeMode(', ')', 'boolean'),
  \ javaapi#method(0,'verifyPendingInstall(', 'int, int)', 'void'),
  \ javaapi#method(0,'extendVerificationTimeout(', 'int, int, long)', 'void'),
  \ ])

call javaapi#class('MockContentResolver', '', [
  \ javaapi#method(0,'MockContentResolver(', ')', 'public'),
  \ javaapi#method(0,'addProvider(', 'String, ContentProvider)', 'void'),
  \ javaapi#method(0,'notifyChange(', 'Uri, ContentObserver, boolean)', 'void'),
  \ ])

call javaapi#class('MockContext', '', [
  \ javaapi#method(0,'MockContext(', ')', 'public'),
  \ javaapi#method(0,'getAssets(', ')', 'AssetManager'),
  \ javaapi#method(0,'getResources(', ')', 'Resources'),
  \ javaapi#method(0,'getPackageManager(', ')', 'PackageManager'),
  \ javaapi#method(0,'getContentResolver(', ')', 'ContentResolver'),
  \ javaapi#method(0,'getMainLooper(', ')', 'Looper'),
  \ javaapi#method(0,'getApplicationContext(', ')', 'Context'),
  \ javaapi#method(0,'setTheme(', 'int)', 'void'),
  \ javaapi#method(0,'getTheme(', ')', 'Theme'),
  \ javaapi#method(0,'getClassLoader(', ')', 'ClassLoader'),
  \ javaapi#method(0,'getPackageName(', ')', 'String'),
  \ javaapi#method(0,'getApplicationInfo(', ')', 'ApplicationInfo'),
  \ javaapi#method(0,'getPackageResourcePath(', ')', 'String'),
  \ javaapi#method(0,'getPackageCodePath(', ')', 'String'),
  \ javaapi#method(0,'getSharedPreferences(', 'String, int)', 'SharedPreferences'),
  \ javaapi#method(0,'openFileInput(', 'String) throws FileNotFoundException', 'FileInputStream'),
  \ javaapi#method(0,'openFileOutput(', 'String, int) throws FileNotFoundException', 'FileOutputStream'),
  \ javaapi#method(0,'deleteFile(', 'String)', 'boolean'),
  \ javaapi#method(0,'getFileStreamPath(', 'String)', 'File'),
  \ javaapi#method(0,'fileList(', ')', 'String[]'),
  \ javaapi#method(0,'getFilesDir(', ')', 'File'),
  \ javaapi#method(0,'getExternalFilesDir(', 'String)', 'File'),
  \ javaapi#method(0,'getObbDir(', ')', 'File'),
  \ javaapi#method(0,'getCacheDir(', ')', 'File'),
  \ javaapi#method(0,'getExternalCacheDir(', ')', 'File'),
  \ javaapi#method(0,'getDir(', 'String, int)', 'File'),
  \ javaapi#method(0,'openOrCreateDatabase(', 'String, int, CursorFactory)', 'SQLiteDatabase'),
  \ javaapi#method(0,'openOrCreateDatabase(', 'String, int, CursorFactory, DatabaseErrorHandler)', 'SQLiteDatabase'),
  \ javaapi#method(0,'getDatabasePath(', 'String)', 'File'),
  \ javaapi#method(0,'databaseList(', ')', 'String[]'),
  \ javaapi#method(0,'deleteDatabase(', 'String)', 'boolean'),
  \ javaapi#method(0,'getWallpaper(', ')', 'Drawable'),
  \ javaapi#method(0,'peekWallpaper(', ')', 'Drawable'),
  \ javaapi#method(0,'getWallpaperDesiredMinimumWidth(', ')', 'int'),
  \ javaapi#method(0,'getWallpaperDesiredMinimumHeight(', ')', 'int'),
  \ javaapi#method(0,'setWallpaper(', 'Bitmap) throws IOException', 'void'),
  \ javaapi#method(0,'setWallpaper(', 'InputStream) throws IOException', 'void'),
  \ javaapi#method(0,'clearWallpaper(', ')', 'void'),
  \ javaapi#method(0,'startActivity(', 'Intent)', 'void'),
  \ javaapi#method(0,'startActivity(', 'Intent, Bundle)', 'void'),
  \ javaapi#method(0,'startActivities(', 'Intent[])', 'void'),
  \ javaapi#method(0,'startActivities(', 'Intent[], Bundle)', 'void'),
  \ javaapi#method(0,'startIntentSender(', 'IntentSender, Intent, int, int, int) throws SendIntentException', 'void'),
  \ javaapi#method(0,'startIntentSender(', 'IntentSender, Intent, int, int, int, Bundle) throws SendIntentException', 'void'),
  \ javaapi#method(0,'sendBroadcast(', 'Intent)', 'void'),
  \ javaapi#method(0,'sendBroadcast(', 'Intent, String)', 'void'),
  \ javaapi#method(0,'sendOrderedBroadcast(', 'Intent, String)', 'void'),
  \ javaapi#method(0,'sendOrderedBroadcast(', 'Intent, String, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,'sendBroadcastAsUser(', 'Intent, UserHandle)', 'void'),
  \ javaapi#method(0,'sendBroadcastAsUser(', 'Intent, UserHandle, String)', 'void'),
  \ javaapi#method(0,'sendOrderedBroadcastAsUser(', 'Intent, UserHandle, String, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,'sendStickyBroadcast(', 'Intent)', 'void'),
  \ javaapi#method(0,'sendStickyOrderedBroadcast(', 'Intent, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,'removeStickyBroadcast(', 'Intent)', 'void'),
  \ javaapi#method(0,'sendStickyBroadcastAsUser(', 'Intent, UserHandle)', 'void'),
  \ javaapi#method(0,'sendStickyOrderedBroadcastAsUser(', 'Intent, UserHandle, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,'removeStickyBroadcastAsUser(', 'Intent, UserHandle)', 'void'),
  \ javaapi#method(0,'registerReceiver(', 'BroadcastReceiver, IntentFilter)', 'Intent'),
  \ javaapi#method(0,'registerReceiver(', 'BroadcastReceiver, IntentFilter, String, Handler)', 'Intent'),
  \ javaapi#method(0,'unregisterReceiver(', 'BroadcastReceiver)', 'void'),
  \ javaapi#method(0,'startService(', 'Intent)', 'ComponentName'),
  \ javaapi#method(0,'stopService(', 'Intent)', 'boolean'),
  \ javaapi#method(0,'bindService(', 'Intent, ServiceConnection, int)', 'boolean'),
  \ javaapi#method(0,'unbindService(', 'ServiceConnection)', 'void'),
  \ javaapi#method(0,'startInstrumentation(', 'ComponentName, String, Bundle)', 'boolean'),
  \ javaapi#method(0,'getSystemService(', 'String)', 'Object'),
  \ javaapi#method(0,'checkPermission(', 'String, int, int)', 'int'),
  \ javaapi#method(0,'checkCallingPermission(', 'String)', 'int'),
  \ javaapi#method(0,'checkCallingOrSelfPermission(', 'String)', 'int'),
  \ javaapi#method(0,'enforcePermission(', 'String, int, int, String)', 'void'),
  \ javaapi#method(0,'enforceCallingPermission(', 'String, String)', 'void'),
  \ javaapi#method(0,'enforceCallingOrSelfPermission(', 'String, String)', 'void'),
  \ javaapi#method(0,'grantUriPermission(', 'String, Uri, int)', 'void'),
  \ javaapi#method(0,'revokeUriPermission(', 'Uri, int)', 'void'),
  \ javaapi#method(0,'checkUriPermission(', 'Uri, int, int, int)', 'int'),
  \ javaapi#method(0,'checkCallingUriPermission(', 'Uri, int)', 'int'),
  \ javaapi#method(0,'checkCallingOrSelfUriPermission(', 'Uri, int)', 'int'),
  \ javaapi#method(0,'checkUriPermission(', 'Uri, String, String, int, int, int)', 'int'),
  \ javaapi#method(0,'enforceUriPermission(', 'Uri, int, int, int, String)', 'void'),
  \ javaapi#method(0,'enforceCallingUriPermission(', 'Uri, int, String)', 'void'),
  \ javaapi#method(0,'enforceCallingOrSelfUriPermission(', 'Uri, int, String)', 'void'),
  \ javaapi#method(0,'enforceUriPermission(', 'Uri, String, String, int, int, int, String)', 'void'),
  \ javaapi#method(0,'createPackageContext(', 'String, int) throws NameNotFoundException', 'Context'),
  \ javaapi#method(0,'createConfigurationContext(', 'Configuration)', 'Context'),
  \ javaapi#method(0,'createDisplayContext(', 'Display)', 'Context'),
  \ javaapi#method(0,'isRestricted(', ')', 'boolean'),
  \ ])

call javaapi#class('MockContentProvider', '', [
  \ javaapi#method(0,'MockContentProvider(', 'Context)', 'public'),
  \ javaapi#method(0,'MockContentProvider(', 'Context, String, String, PathPermission[])', 'public'),
  \ javaapi#method(0,'delete(', 'Uri, String, String[])', 'int'),
  \ javaapi#method(0,'getType(', 'Uri)', 'String'),
  \ javaapi#method(0,'insert(', 'Uri, ContentValues)', 'Uri'),
  \ javaapi#method(0,'onCreate(', ')', 'boolean'),
  \ javaapi#method(0,'query(', 'Uri, String[], String, String[], String)', 'Cursor'),
  \ javaapi#method(0,'update(', 'Uri, ContentValues, String, String[])', 'int'),
  \ javaapi#method(0,'bulkInsert(', 'Uri, ContentValues[])', 'int'),
  \ javaapi#method(0,'attachInfo(', 'Context, ProviderInfo)', 'void'),
  \ javaapi#method(0,'applyBatch(', 'ArrayList<ContentProviderOperation>)', 'ContentProviderResult[]'),
  \ javaapi#method(0,'getStreamTypes(', 'Uri, String)', 'String[]'),
  \ javaapi#method(0,'openTypedAssetFile(', 'Uri, String, Bundle)', 'AssetFileDescriptor'),
  \ ])

call javaapi#class('MockResources', '', [
  \ javaapi#method(0,'MockResources(', ')', 'public'),
  \ javaapi#method(0,'updateConfiguration(', 'Configuration, DisplayMetrics)', 'void'),
  \ javaapi#method(0,'getText(', 'int) throws NotFoundException', 'CharSequence'),
  \ javaapi#method(0,'getQuantityText(', 'int, int) throws NotFoundException', 'CharSequence'),
  \ javaapi#method(0,'getString(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,'getString(', 'int, ) throws NotFoundException', 'String'),
  \ javaapi#method(0,'getQuantityString(', 'int, int, ) throws NotFoundException', 'String'),
  \ javaapi#method(0,'getQuantityString(', 'int, int) throws NotFoundException', 'String'),
  \ javaapi#method(0,'getText(', 'int, CharSequence)', 'CharSequence'),
  \ javaapi#method(0,'getTextArray(', 'int) throws NotFoundException', 'CharSequence[]'),
  \ javaapi#method(0,'getStringArray(', 'int) throws NotFoundException', 'String[]'),
  \ javaapi#method(0,'getIntArray(', 'int) throws NotFoundException', 'int[]'),
  \ javaapi#method(0,'obtainTypedArray(', 'int) throws NotFoundException', 'TypedArray'),
  \ javaapi#method(0,'getDimension(', 'int) throws NotFoundException', 'float'),
  \ javaapi#method(0,'getDimensionPixelOffset(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,'getDimensionPixelSize(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,'getDrawable(', 'int) throws NotFoundException', 'Drawable'),
  \ javaapi#method(0,'getMovie(', 'int) throws NotFoundException', 'Movie'),
  \ javaapi#method(0,'getColor(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,'getColorStateList(', 'int) throws NotFoundException', 'ColorStateList'),
  \ javaapi#method(0,'getInteger(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,'getLayout(', 'int) throws NotFoundException', 'XmlResourceParser'),
  \ javaapi#method(0,'getAnimation(', 'int) throws NotFoundException', 'XmlResourceParser'),
  \ javaapi#method(0,'getXml(', 'int) throws NotFoundException', 'XmlResourceParser'),
  \ javaapi#method(0,'openRawResource(', 'int) throws NotFoundException', 'InputStream'),
  \ javaapi#method(0,'openRawResourceFd(', 'int) throws NotFoundException', 'AssetFileDescriptor'),
  \ javaapi#method(0,'getValue(', 'int, TypedValue, boolean) throws NotFoundException', 'void'),
  \ javaapi#method(0,'getValue(', 'String, TypedValue, boolean) throws NotFoundException', 'void'),
  \ javaapi#method(0,'obtainAttributes(', 'AttributeSet, int[])', 'TypedArray'),
  \ javaapi#method(0,'getDisplayMetrics(', ')', 'DisplayMetrics'),
  \ javaapi#method(0,'getConfiguration(', ')', 'Configuration'),
  \ javaapi#method(0,'getIdentifier(', 'String, String, String)', 'int'),
  \ javaapi#method(0,'getResourceName(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,'getResourcePackageName(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,'getResourceTypeName(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,'getResourceEntryName(', 'int) throws NotFoundException', 'String'),
  \ ])

