call javaapi#namespace('android.test.mock')

call javaapi#class('MockApplication', 'Application', [
  \ javaapi#method(0,1,'MockApplication(', ')', ''),
  \ javaapi#method(0,1,'onCreate(', ')', 'void'),
  \ javaapi#method(0,1,'onTerminate(', ')', 'void'),
  \ javaapi#method(0,1,'onConfigurationChanged(', 'Configuration)', 'void'),
  \ ])

call javaapi#class('MockCursor', 'Cursor', [
  \ javaapi#method(0,1,'MockCursor(', ')', ''),
  \ javaapi#method(0,1,'getColumnCount(', ')', 'int'),
  \ javaapi#method(0,1,'getColumnIndex(', 'String)', 'int'),
  \ javaapi#method(0,1,'getColumnIndexOrThrow(', 'String)', 'int'),
  \ javaapi#method(0,1,'getColumnName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getColumnNames(', ')', 'String'),
  \ javaapi#method(0,1,'getCount(', ')', 'int'),
  \ javaapi#method(0,1,'isNull(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'getInt(', 'int)', 'int'),
  \ javaapi#method(0,1,'getLong(', 'int)', 'long'),
  \ javaapi#method(0,1,'getShort(', 'int)', 'short'),
  \ javaapi#method(0,1,'getFloat(', 'int)', 'float'),
  \ javaapi#method(0,1,'getDouble(', 'int)', 'double'),
  \ javaapi#method(0,1,'getBlob(', 'int)', 'byte'),
  \ javaapi#method(0,1,'getString(', 'int)', 'String'),
  \ javaapi#method(0,1,'getExtras(', ')', 'Bundle'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'isAfterLast(', ')', 'boolean'),
  \ javaapi#method(0,1,'isBeforeFirst(', ')', 'boolean'),
  \ javaapi#method(0,1,'isFirst(', ')', 'boolean'),
  \ javaapi#method(0,1,'isLast(', ')', 'boolean'),
  \ javaapi#method(0,1,'move(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'moveToFirst(', ')', 'boolean'),
  \ javaapi#method(0,1,'moveToLast(', ')', 'boolean'),
  \ javaapi#method(0,1,'moveToNext(', ')', 'boolean'),
  \ javaapi#method(0,1,'moveToPrevious(', ')', 'boolean'),
  \ javaapi#method(0,1,'moveToPosition(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'copyStringToBuffer(', 'int, CharArrayBuffer)', 'void'),
  \ javaapi#method(0,1,'deactivate(', ')', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'isClosed(', ')', 'boolean'),
  \ javaapi#method(0,1,'requery(', ')', 'boolean'),
  \ javaapi#method(0,1,'registerContentObserver(', 'ContentObserver)', 'void'),
  \ javaapi#method(0,1,'registerDataSetObserver(', 'DataSetObserver)', 'void'),
  \ javaapi#method(0,1,'respond(', 'Bundle)', 'Bundle'),
  \ javaapi#method(0,1,'getWantsAllOnMoveCalls(', ')', 'boolean'),
  \ javaapi#method(0,1,'setNotificationUri(', 'ContentResolver, Uri)', 'void'),
  \ javaapi#method(0,1,'unregisterContentObserver(', 'ContentObserver)', 'void'),
  \ javaapi#method(0,1,'unregisterDataSetObserver(', 'DataSetObserver)', 'void'),
  \ javaapi#method(0,1,'getType(', 'int)', 'int'),
  \ ])

call javaapi#class('MockDialogInterface', 'DialogInterface', [
  \ javaapi#method(0,1,'MockDialogInterface(', ')', ''),
  \ javaapi#method(0,1,'cancel(', ')', 'void'),
  \ javaapi#method(0,1,'dismiss(', ')', 'void'),
  \ ])

call javaapi#class('MockPackageManager', 'PackageManager', [
  \ javaapi#method(0,1,'MockPackageManager(', ')', ''),
  \ javaapi#method(0,1,'getPackageInfo(', 'String, int) throws NameNotFoundException', 'PackageInfo'),
  \ javaapi#method(0,1,'currentToCanonicalPackageNames(', 'String[])', 'String'),
  \ javaapi#method(0,1,'canonicalToCurrentPackageNames(', 'String[])', 'String'),
  \ javaapi#method(0,1,'getLaunchIntentForPackage(', 'String)', 'Intent'),
  \ javaapi#method(0,1,'getPackageGids(', 'String) throws NameNotFoundException', 'int'),
  \ javaapi#method(0,1,'getPermissionInfo(', 'String, int) throws NameNotFoundException', 'PermissionInfo'),
  \ javaapi#method(0,1,'queryPermissionsByGroup(', 'String, int) throws NameNotFoundException', 'List'),
  \ javaapi#method(0,1,'getPermissionGroupInfo(', 'String, int) throws NameNotFoundException', 'PermissionGroupInfo'),
  \ javaapi#method(0,1,'getAllPermissionGroups(', 'int)', 'List'),
  \ javaapi#method(0,1,'getApplicationInfo(', 'String, int) throws NameNotFoundException', 'ApplicationInfo'),
  \ javaapi#method(0,1,'getActivityInfo(', 'ComponentName, int) throws NameNotFoundException', 'ActivityInfo'),
  \ javaapi#method(0,1,'getReceiverInfo(', 'ComponentName, int) throws NameNotFoundException', 'ActivityInfo'),
  \ javaapi#method(0,1,'getServiceInfo(', 'ComponentName, int) throws NameNotFoundException', 'ServiceInfo'),
  \ javaapi#method(0,1,'getProviderInfo(', 'ComponentName, int) throws NameNotFoundException', 'ProviderInfo'),
  \ javaapi#method(0,1,'getInstalledPackages(', 'int)', 'List'),
  \ javaapi#method(0,1,'checkPermission(', 'String, String)', 'int'),
  \ javaapi#method(0,1,'addPermission(', 'PermissionInfo)', 'boolean'),
  \ javaapi#method(0,1,'addPermissionAsync(', 'PermissionInfo)', 'boolean'),
  \ javaapi#method(0,1,'removePermission(', 'String)', 'void'),
  \ javaapi#method(0,1,'checkSignatures(', 'String, String)', 'int'),
  \ javaapi#method(0,1,'checkSignatures(', 'int, int)', 'int'),
  \ javaapi#method(0,1,'getPackagesForUid(', 'int)', 'String'),
  \ javaapi#method(0,1,'getNameForUid(', 'int)', 'String'),
  \ javaapi#method(0,1,'getInstalledApplications(', 'int)', 'List'),
  \ javaapi#method(0,1,'resolveActivity(', 'Intent, int)', 'ResolveInfo'),
  \ javaapi#method(0,1,'queryIntentActivities(', 'Intent, int)', 'List'),
  \ javaapi#method(0,1,'queryIntentActivityOptions(', 'ComponentName, Intent[], Intent, int)', 'List'),
  \ javaapi#method(0,1,'queryBroadcastReceivers(', 'Intent, int)', 'List'),
  \ javaapi#method(0,1,'resolveService(', 'Intent, int)', 'ResolveInfo'),
  \ javaapi#method(0,1,'queryIntentServices(', 'Intent, int)', 'List'),
  \ javaapi#method(0,1,'resolveContentProvider(', 'String, int)', 'ProviderInfo'),
  \ javaapi#method(0,1,'queryContentProviders(', 'String, int, int)', 'List'),
  \ javaapi#method(0,1,'getInstrumentationInfo(', 'ComponentName, int) throws NameNotFoundException', 'InstrumentationInfo'),
  \ javaapi#method(0,1,'queryInstrumentation(', 'String, int)', 'List'),
  \ javaapi#method(0,1,'getDrawable(', 'String, int, ApplicationInfo)', 'Drawable'),
  \ javaapi#method(0,1,'getActivityIcon(', 'ComponentName) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,1,'getActivityIcon(', 'Intent) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,1,'getDefaultActivityIcon(', ')', 'Drawable'),
  \ javaapi#method(0,1,'getApplicationIcon(', 'ApplicationInfo)', 'Drawable'),
  \ javaapi#method(0,1,'getApplicationIcon(', 'String) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,1,'getActivityLogo(', 'ComponentName) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,1,'getActivityLogo(', 'Intent) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,1,'getApplicationLogo(', 'ApplicationInfo)', 'Drawable'),
  \ javaapi#method(0,1,'getApplicationLogo(', 'String) throws NameNotFoundException', 'Drawable'),
  \ javaapi#method(0,1,'getText(', 'String, int, ApplicationInfo)', 'CharSequence'),
  \ javaapi#method(0,1,'getXml(', 'String, int, ApplicationInfo)', 'XmlResourceParser'),
  \ javaapi#method(0,1,'getApplicationLabel(', 'ApplicationInfo)', 'CharSequence'),
  \ javaapi#method(0,1,'getResourcesForActivity(', 'ComponentName) throws NameNotFoundException', 'Resources'),
  \ javaapi#method(0,1,'getResourcesForApplication(', 'ApplicationInfo)', 'Resources'),
  \ javaapi#method(0,1,'getResourcesForApplication(', 'String) throws NameNotFoundException', 'Resources'),
  \ javaapi#method(0,1,'getPackageArchiveInfo(', 'String, int)', 'PackageInfo'),
  \ javaapi#method(0,1,'setInstallerPackageName(', 'String, String)', 'void'),
  \ javaapi#method(0,1,'getInstallerPackageName(', 'String)', 'String'),
  \ javaapi#method(0,1,'addPackageToPreferred(', 'String)', 'void'),
  \ javaapi#method(0,1,'removePackageFromPreferred(', 'String)', 'void'),
  \ javaapi#method(0,1,'getPreferredPackages(', 'int)', 'List'),
  \ javaapi#method(0,1,'setComponentEnabledSetting(', 'ComponentName, int, int)', 'void'),
  \ javaapi#method(0,1,'getComponentEnabledSetting(', 'ComponentName)', 'int'),
  \ javaapi#method(0,1,'setApplicationEnabledSetting(', 'String, int, int)', 'void'),
  \ javaapi#method(0,1,'getApplicationEnabledSetting(', 'String)', 'int'),
  \ javaapi#method(0,1,'addPreferredActivity(', 'IntentFilter, int, ComponentName[], ComponentName)', 'void'),
  \ javaapi#method(0,1,'clearPackagePreferredActivities(', 'String)', 'void'),
  \ javaapi#method(0,1,'getPreferredActivities(', 'List<IntentFilter>, List<ComponentName>, String)', 'int'),
  \ javaapi#method(0,1,'getSystemSharedLibraryNames(', ')', 'String'),
  \ javaapi#method(0,1,'getSystemAvailableFeatures(', ')', 'FeatureInfo'),
  \ javaapi#method(0,1,'hasSystemFeature(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'isSafeMode(', ')', 'boolean'),
  \ javaapi#method(0,1,'verifyPendingInstall(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'extendVerificationTimeout(', 'int, int, long)', 'void'),
  \ ])

call javaapi#class('MockContentResolver', 'ContentResolver', [
  \ javaapi#method(0,1,'MockContentResolver(', ')', ''),
  \ javaapi#method(0,1,'addProvider(', 'String, ContentProvider)', 'void'),
  \ javaapi#method(0,1,'notifyChange(', 'Uri, ContentObserver, boolean)', 'void'),
  \ ])

call javaapi#class('MockContext', 'Context', [
  \ javaapi#method(0,1,'MockContext(', ')', ''),
  \ javaapi#method(0,1,'getAssets(', ')', 'AssetManager'),
  \ javaapi#method(0,1,'getResources(', ')', 'Resources'),
  \ javaapi#method(0,1,'getPackageManager(', ')', 'PackageManager'),
  \ javaapi#method(0,1,'getContentResolver(', ')', 'ContentResolver'),
  \ javaapi#method(0,1,'getMainLooper(', ')', 'Looper'),
  \ javaapi#method(0,1,'getApplicationContext(', ')', 'Context'),
  \ javaapi#method(0,1,'setTheme(', 'int)', 'void'),
  \ javaapi#method(0,1,'getTheme(', ')', 'Theme'),
  \ javaapi#method(0,1,'getClassLoader(', ')', 'ClassLoader'),
  \ javaapi#method(0,1,'getPackageName(', ')', 'String'),
  \ javaapi#method(0,1,'getApplicationInfo(', ')', 'ApplicationInfo'),
  \ javaapi#method(0,1,'getPackageResourcePath(', ')', 'String'),
  \ javaapi#method(0,1,'getPackageCodePath(', ')', 'String'),
  \ javaapi#method(0,1,'getSharedPreferences(', 'String, int)', 'SharedPreferences'),
  \ javaapi#method(0,1,'openFileInput(', 'String) throws FileNotFoundException', 'FileInputStream'),
  \ javaapi#method(0,1,'openFileOutput(', 'String, int) throws FileNotFoundException', 'FileOutputStream'),
  \ javaapi#method(0,1,'deleteFile(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'getFileStreamPath(', 'String)', 'File'),
  \ javaapi#method(0,1,'fileList(', ')', 'String'),
  \ javaapi#method(0,1,'getFilesDir(', ')', 'File'),
  \ javaapi#method(0,1,'getExternalFilesDir(', 'String)', 'File'),
  \ javaapi#method(0,1,'getObbDir(', ')', 'File'),
  \ javaapi#method(0,1,'getCacheDir(', ')', 'File'),
  \ javaapi#method(0,1,'getExternalCacheDir(', ')', 'File'),
  \ javaapi#method(0,1,'getDir(', 'String, int)', 'File'),
  \ javaapi#method(0,1,'openOrCreateDatabase(', 'String, int, CursorFactory)', 'SQLiteDatabase'),
  \ javaapi#method(0,1,'openOrCreateDatabase(', 'String, int, CursorFactory, DatabaseErrorHandler)', 'SQLiteDatabase'),
  \ javaapi#method(0,1,'getDatabasePath(', 'String)', 'File'),
  \ javaapi#method(0,1,'databaseList(', ')', 'String'),
  \ javaapi#method(0,1,'deleteDatabase(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'getWallpaper(', ')', 'Drawable'),
  \ javaapi#method(0,1,'peekWallpaper(', ')', 'Drawable'),
  \ javaapi#method(0,1,'getWallpaperDesiredMinimumWidth(', ')', 'int'),
  \ javaapi#method(0,1,'getWallpaperDesiredMinimumHeight(', ')', 'int'),
  \ javaapi#method(0,1,'setWallpaper(', 'Bitmap) throws IOException', 'void'),
  \ javaapi#method(0,1,'setWallpaper(', 'InputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'clearWallpaper(', ')', 'void'),
  \ javaapi#method(0,1,'startActivity(', 'Intent)', 'void'),
  \ javaapi#method(0,1,'startActivity(', 'Intent, Bundle)', 'void'),
  \ javaapi#method(0,1,'startActivities(', 'Intent[])', 'void'),
  \ javaapi#method(0,1,'startActivities(', 'Intent[], Bundle)', 'void'),
  \ javaapi#method(0,1,'startIntentSender(', 'IntentSender, Intent, int, int, int) throws SendIntentException', 'void'),
  \ javaapi#method(0,1,'startIntentSender(', 'IntentSender, Intent, int, int, int, Bundle) throws SendIntentException', 'void'),
  \ javaapi#method(0,1,'sendBroadcast(', 'Intent)', 'void'),
  \ javaapi#method(0,1,'sendBroadcast(', 'Intent, String)', 'void'),
  \ javaapi#method(0,1,'sendOrderedBroadcast(', 'Intent, String)', 'void'),
  \ javaapi#method(0,1,'sendOrderedBroadcast(', 'Intent, String, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,1,'sendBroadcastAsUser(', 'Intent, UserHandle)', 'void'),
  \ javaapi#method(0,1,'sendBroadcastAsUser(', 'Intent, UserHandle, String)', 'void'),
  \ javaapi#method(0,1,'sendOrderedBroadcastAsUser(', 'Intent, UserHandle, String, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,1,'sendStickyBroadcast(', 'Intent)', 'void'),
  \ javaapi#method(0,1,'sendStickyOrderedBroadcast(', 'Intent, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,1,'removeStickyBroadcast(', 'Intent)', 'void'),
  \ javaapi#method(0,1,'sendStickyBroadcastAsUser(', 'Intent, UserHandle)', 'void'),
  \ javaapi#method(0,1,'sendStickyOrderedBroadcastAsUser(', 'Intent, UserHandle, BroadcastReceiver, Handler, int, String, Bundle)', 'void'),
  \ javaapi#method(0,1,'removeStickyBroadcastAsUser(', 'Intent, UserHandle)', 'void'),
  \ javaapi#method(0,1,'registerReceiver(', 'BroadcastReceiver, IntentFilter)', 'Intent'),
  \ javaapi#method(0,1,'registerReceiver(', 'BroadcastReceiver, IntentFilter, String, Handler)', 'Intent'),
  \ javaapi#method(0,1,'unregisterReceiver(', 'BroadcastReceiver)', 'void'),
  \ javaapi#method(0,1,'startService(', 'Intent)', 'ComponentName'),
  \ javaapi#method(0,1,'stopService(', 'Intent)', 'boolean'),
  \ javaapi#method(0,1,'bindService(', 'Intent, ServiceConnection, int)', 'boolean'),
  \ javaapi#method(0,1,'unbindService(', 'ServiceConnection)', 'void'),
  \ javaapi#method(0,1,'startInstrumentation(', 'ComponentName, String, Bundle)', 'boolean'),
  \ javaapi#method(0,1,'getSystemService(', 'String)', 'Object'),
  \ javaapi#method(0,1,'checkPermission(', 'String, int, int)', 'int'),
  \ javaapi#method(0,1,'checkCallingPermission(', 'String)', 'int'),
  \ javaapi#method(0,1,'checkCallingOrSelfPermission(', 'String)', 'int'),
  \ javaapi#method(0,1,'enforcePermission(', 'String, int, int, String)', 'void'),
  \ javaapi#method(0,1,'enforceCallingPermission(', 'String, String)', 'void'),
  \ javaapi#method(0,1,'enforceCallingOrSelfPermission(', 'String, String)', 'void'),
  \ javaapi#method(0,1,'grantUriPermission(', 'String, Uri, int)', 'void'),
  \ javaapi#method(0,1,'revokeUriPermission(', 'Uri, int)', 'void'),
  \ javaapi#method(0,1,'checkUriPermission(', 'Uri, int, int, int)', 'int'),
  \ javaapi#method(0,1,'checkCallingUriPermission(', 'Uri, int)', 'int'),
  \ javaapi#method(0,1,'checkCallingOrSelfUriPermission(', 'Uri, int)', 'int'),
  \ javaapi#method(0,1,'checkUriPermission(', 'Uri, String, String, int, int, int)', 'int'),
  \ javaapi#method(0,1,'enforceUriPermission(', 'Uri, int, int, int, String)', 'void'),
  \ javaapi#method(0,1,'enforceCallingUriPermission(', 'Uri, int, String)', 'void'),
  \ javaapi#method(0,1,'enforceCallingOrSelfUriPermission(', 'Uri, int, String)', 'void'),
  \ javaapi#method(0,1,'enforceUriPermission(', 'Uri, String, String, int, int, int, String)', 'void'),
  \ javaapi#method(0,1,'createPackageContext(', 'String, int) throws NameNotFoundException', 'Context'),
  \ javaapi#method(0,1,'createConfigurationContext(', 'Configuration)', 'Context'),
  \ javaapi#method(0,1,'createDisplayContext(', 'Display)', 'Context'),
  \ javaapi#method(0,1,'isRestricted(', ')', 'boolean'),
  \ ])

call javaapi#class('MockContentProvider', 'ContentProvider', [
  \ javaapi#method(0,0,'MockContentProvider(', ')', ''),
  \ javaapi#method(0,1,'MockContentProvider(', 'Context)', ''),
  \ javaapi#method(0,1,'MockContentProvider(', 'Context, String, String, PathPermission[])', ''),
  \ javaapi#method(0,1,'delete(', 'Uri, String, String[])', 'int'),
  \ javaapi#method(0,1,'getType(', 'Uri)', 'String'),
  \ javaapi#method(0,1,'insert(', 'Uri, ContentValues)', 'Uri'),
  \ javaapi#method(0,1,'onCreate(', ')', 'boolean'),
  \ javaapi#method(0,1,'query(', 'Uri, String[], String, String[], String)', 'Cursor'),
  \ javaapi#method(0,1,'update(', 'Uri, ContentValues, String, String[])', 'int'),
  \ javaapi#method(0,1,'bulkInsert(', 'Uri, ContentValues[])', 'int'),
  \ javaapi#method(0,1,'attachInfo(', 'Context, ProviderInfo)', 'void'),
  \ javaapi#method(0,1,'applyBatch(', 'ArrayList<ContentProviderOperation>)', 'ContentProviderResult'),
  \ javaapi#method(0,1,'getStreamTypes(', 'Uri, String)', 'String'),
  \ javaapi#method(0,1,'openTypedAssetFile(', 'Uri, String, Bundle)', 'AssetFileDescriptor'),
  \ ])

call javaapi#class('MockResources', 'Resources', [
  \ javaapi#method(0,1,'MockResources(', ')', ''),
  \ javaapi#method(0,1,'updateConfiguration(', 'Configuration, DisplayMetrics)', 'void'),
  \ javaapi#method(0,1,'getText(', 'int) throws NotFoundException', 'CharSequence'),
  \ javaapi#method(0,1,'getQuantityText(', 'int, int) throws NotFoundException', 'CharSequence'),
  \ javaapi#method(0,1,'getString(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getString(', 'int, ) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getQuantityString(', 'int, int, ) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getQuantityString(', 'int, int) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getText(', 'int, CharSequence)', 'CharSequence'),
  \ javaapi#method(0,1,'getTextArray(', 'int) throws NotFoundException', 'CharSequence'),
  \ javaapi#method(0,1,'getStringArray(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getIntArray(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,1,'obtainTypedArray(', 'int) throws NotFoundException', 'TypedArray'),
  \ javaapi#method(0,1,'getDimension(', 'int) throws NotFoundException', 'float'),
  \ javaapi#method(0,1,'getDimensionPixelOffset(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,1,'getDimensionPixelSize(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,1,'getDrawable(', 'int) throws NotFoundException', 'Drawable'),
  \ javaapi#method(0,1,'getMovie(', 'int) throws NotFoundException', 'Movie'),
  \ javaapi#method(0,1,'getColor(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,1,'getColorStateList(', 'int) throws NotFoundException', 'ColorStateList'),
  \ javaapi#method(0,1,'getInteger(', 'int) throws NotFoundException', 'int'),
  \ javaapi#method(0,1,'getLayout(', 'int) throws NotFoundException', 'XmlResourceParser'),
  \ javaapi#method(0,1,'getAnimation(', 'int) throws NotFoundException', 'XmlResourceParser'),
  \ javaapi#method(0,1,'getXml(', 'int) throws NotFoundException', 'XmlResourceParser'),
  \ javaapi#method(0,1,'openRawResource(', 'int) throws NotFoundException', 'InputStream'),
  \ javaapi#method(0,1,'openRawResourceFd(', 'int) throws NotFoundException', 'AssetFileDescriptor'),
  \ javaapi#method(0,1,'getValue(', 'int, TypedValue, boolean) throws NotFoundException', 'void'),
  \ javaapi#method(0,1,'getValue(', 'String, TypedValue, boolean) throws NotFoundException', 'void'),
  \ javaapi#method(0,1,'obtainAttributes(', 'AttributeSet, int[])', 'TypedArray'),
  \ javaapi#method(0,1,'getDisplayMetrics(', ')', 'DisplayMetrics'),
  \ javaapi#method(0,1,'getConfiguration(', ')', 'Configuration'),
  \ javaapi#method(0,1,'getIdentifier(', 'String, String, String)', 'int'),
  \ javaapi#method(0,1,'getResourceName(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getResourcePackageName(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getResourceTypeName(', 'int) throws NotFoundException', 'String'),
  \ javaapi#method(0,1,'getResourceEntryName(', 'int) throws NotFoundException', 'String'),
  \ ])

